### ISSUE TITLE
Support queries for arrays of primitives

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#513]
This is a meta issue to make it easy to see at a glance the object store's progress towards implementing arrays of primitives.

Subtasks:

* [x] Add support for opening files containing subtable columns (#466)
* [x] Change property type definitions to support arrays of all types (#464)
* [x] Update object accessor implementation to support arrays of primitives (#443)
* [x] Add support for storing and retrieving arrays of all supported data types (#512)
* [x] Add support for queries involving arrays of primitives
  * [ ] Filtering a collection of objects on the values of an array it contains
  * [ ] Filtering an array of primitives

**Comment by bdash** [comment]
@tgoyne, thoughts on closing this since and filing a new issue tracking adding support for queries? The core functionality this issue was tracking has been implemented.

**Comment by Zhuinden** [comment]
https://github.com/realm/realm-java/issues/5361

**Comment by basememara** [comment]
Is this possible yet?

**Comment by basememara** [comment]
Is this possible yet? I thought this would work, but it crashes:

```
class ItemsObject: Object {
  dynamic var categories = List<Int>()
}

let ids: [Int] = [2, 5, 19]

realm.objects(ItemsObject self).filter("ANY categories IN %@", ids)
*** Terminating app due to uncaught exception 'Invalid value', reason: 'Expected object of type (null) in IN clause for property 'categories' on object of type 'ItemsObject', but received: 3'

.filter("SUBQUERY(categories, $id, $id IN %@).@count > 0", ids)
*** Terminating app due to uncaught exception 'RLMException', reason: 'Object type '(null)' not managed by the Realm'
```

**Comment by Zhuinden** [comment]
Milestone RMP 2.0? 🤔

**Comment by aritrobanerjee93** [comment]
This feature is quite crucial. Any updates?

**Comment by Zhuinden** [comment]
🤷‍♂️

**Comment by jordyseynaeve** [comment]
🤔Also need this

**Comment by Andrew51130** [comment]
need this, up

**Comment by L4grange** [comment]
Queries on this primitives list is needed in my opinion, since not being able to query actually defeats the purpose of using a list in my case. I used a concatenated string with a separator for now.

**Comment by cmcnicholas** [comment]
Has there been any further work on querying primitive lists? it would be better for realm to not suggest using them until query support improves, I have implemented quite a large db structure and now need to go and either stringify the data on insert/update for searching or introduce a proxy object, not great.

**Comment by bmunkholm** [comment]
@cmcnicholas Sorry about your trouble with this. I'm happy to say that we will get started on this now.

**Comment by cmcnicholas** [comment]
> @cmcnicholas Sorry about your trouble with this. I'm happy to say that we will get started on this now.

Hero!

**Comment by primeviltom** [comment]
Hi there, 
I too am trying to implement a filtering system where I query a list with an array of strings. 
A fairly basic query like:
`filteredPages = allPages.filter("ANY category IN %@", selectedCategories)`
is crashing with the familiar error:
`Terminating app due to uncaught exception 'Invalid value', reason: 'Expected object of type (null) in IN clause for property 'category' on object of type 'Page', but received: Cafe'`

Does anyone know of a workaround or the correct way to properly query a list with an array of primitives?

**Comment by bmunkholm** [comment]
Support for querying arrays of primitive types has now been implemented in Core and ObjectStore. It's also been exposed in realm-js, just pending release. So I'm closing this issue.
Please refer to the SDK specific issues to follow progress on implementing the support for the  respective SDK:
[Java](https://github.com/realm/realm-java/issues/5361)
[Cocoa](https://github.com/realm/realm-cocoa/issues/5334)
[.NET](https://github.com/realm/realm-dotnet/issues/1979)
